#define CMD_END 0
#define CMD_CLEAR 1
#define CMD_PALETTE 2
#define CMD_FADETO 3
#define CMD_ANIM 4
#define CMD_PAUSE 5
#define CMD_MOD 6
#define CMD_ILBM 7
#define CMD_SOUND 8
#define CMD_STARTEFFECT 9
#define CMD_LOADFONT 10
#define CMD_ALTERNATE_PALETTE 11
#define CMD_USE_ALTERNATE_PALETTE 12
#define CMD_SCENE 13
#define CMD_SCENE_INDEX 14
#define CMD_MBIT 15

